sudo: required
services:
  - docker

language: scala
scala:
  - 2.12.4
sbt_args: -J-Xms2G -J-Xmx2G -J-XX:MaxMetaspaceSize=2G

jdk:
  - oraclejdk8

script:
  - sbt compile
  - sbt test
  - sbt daemon/assembly
  - docker build -t farmdawgnation/kafka-detective:$VERSION .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ ! "$VERSION" == *SNAPSHOT ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push farmdawgnation/kafka-detective:$VERSION;
    fi

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

branches:
  only:
    - master
