sudo: required
services:
  - docker

language: scala
scala:
  - 2.12.4

jdk:
  - oraclejdk8

before_script:
  - docker-compose up -d

script:
  - sbt compile
  - sbt test
  - sbt daemon/it:test
  - sbt daemon/assembly
  - docker build -t farmdawgnation/kafka-detective:$VERSION .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push farmdawgnation/kafka-detective:$VERSION;
    fi

after_script:
  - docker-compose down
